image:
  name: golang:1.22.0-alpine3.19
  entrypoint: ["/bin/sh", "-c"]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - apk add --no-cache make
  - make web

  # Convert symlinks to actual folder because GitLab artifact process skips symlinks
  - cd web
  - mkdir tmp
  - for f in $(find . -type l);do mv $(realpath $f) tmp/$f;rm $f;done;
  - mv tmp/* .

  # Finish
  - cd ../ && mv web public
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
